name: Code checks and testing

on:
  pull_request:
    branches:
      - main

jobs:
  check_and_test:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t workflow-testing -f Dockerfile.tests .

    - name: Run ESLint
      run: docker run --rm workflow-testing npm run lint

    - name: Run Unit Tests
      run: docker run --rm workflow-testing npm run test:unit

    - name: Run E2E Tests
      run: docker run --rm --network host workflow-testing npm run test:e2e

    - name: Run Type Checking
      run: docker run --rm workflow-testing npm run check

    - name: Build Project
      run: docker run --rm workflow-testing npm run build
